// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpahMw3-ihEGFA70EedQhWL0RelaK5tnM',
    appId: '1:222267322028:web:79ee9601d9c605e4587909',
    messagingSenderId: '222267322028',
    projectId: 'chat-application-61d1b',
    authDomain: 'chat-application-61d1b.firebaseapp.com',
    storageBucket: 'chat-application-61d1b.appspot.com',
    measurementId: 'G-KGV2RXKJ9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRnBAtlbdHnKLH_CNqmh7HI8feVnTu1RU',
    appId: '1:222267322028:android:db4714c0defc6ec9587909',
    messagingSenderId: '222267322028',
    projectId: 'chat-application-61d1b',
    storageBucket: 'chat-application-61d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyf2tWcEiRigLf_NVLRpXmbPsaODU6q5E',
    appId: '1:222267322028:ios:6e80559e9763b524587909',
    messagingSenderId: '222267322028',
    projectId: 'chat-application-61d1b',
    storageBucket: 'chat-application-61d1b.appspot.com',
    iosClientId: '222267322028-d2d6i4eq6savn8l85fkjlfndvquu2rf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiLoginRegisterFlutter',
  );
}
